version: '3.2'

services:
  api-certificados:
    container_name: agent-market-go
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    expose:
      - 8100
    networks:
      - agente
    restart: always
networks:
  agente:
    driver: bridge