version: '3.2'

services:
  agent-market-go:
    container_name: agent-market-go
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - 8100:8100
    networks:
      - agente
    restart: always
networks:
  agente:
    driver: bridge